// Renomme le nom du ficher dans page avec des crochets si le nom de la page url est une variable 

'use client'

import { NextPageContext } from 'next'
import Head from 'next/head'
import Success from '@/Components/Success'

// Correspond au Front
export default function Home(props: any) {
    console.log(props)
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        
      <main>
       <Success title={props.data.id}/>   
      </main>
      </>
    ) 
  }


//Correspond au back
export async function getServerSideProps(context: NextPageContext) {
    // Fetch data from external API
  
    const data = context.query
   
    // Pass data to the page via props
    return { props: { data } }
  }